#+TITLE: Emacs configuration

This [[https://github.com/asherbender/emacs-dot-files][repository]] simultaneously contains and documents my [[https://www.gnu.org/software/emacs/][GNU Emacs]]
configuration using the [[http://orgmode.org/worg/org-contrib/babel/intro.html#literate-emacs-init][literate initialisation]] style. The
configuration is written using org-mode and executed using
=org-babel-load-file=. The [[https://github.com/asherbender/emacs-dot-files/blob/master/init.el][init.el]] file is only used to boot-strap the
process.

The main aims and features of this configuration are:

- Literate programming paradigm via Org-mode [[http://orgmode.org/worg/org-contrib/babel/][Babel]]
- Configuration simultaneously versioned and documented on GitHub
- Package installation and updates managed by [[https://github.com/jwiegley/use-package][use-package]]
- Modular configuration

** General

| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-general.org][General]]      | Basic user interface settings                  |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-line-column.org][Line numbers]] | Line and column numbering                      |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-global-map.org][Global map]]   | Define modifications to global key map         |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-backup.org][Backups]]      | Configure backup~ and #auto-save# management   |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-spelling.org][Spelling]]     | Spelling program and on-the-fly spell checking |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-undo-tree.org][Undo]]         | Configure undo system                          |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-whitespace.org][Whitespace]]   | Whitespace management                          |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-recentf.org][Recent files]] | Configure recently opened files management     |

#+begin_src emacs-lisp :exports none
(load-org-config "init-general.org")
(load-org-config "init-line-column.org")
(load-org-config "init-global-map.org")
(load-org-config "init-backup.org")
(load-org-config "init-spelling.org")
(load-org-config "init-undo-tree.org")
(load-org-config "init-whitespace.org")
(load-org-config "init-recentf.org")
#+end_src

** Navigation

| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-hydra.org][Hydra]]   | Hydra menu definitions                         |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-navigation.org][Cursor]]  | Modifications to default cursor movements      |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-isearch.org][isearch]] | Incremental search                             |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-window.org][Window]]  | Window movement and management                 |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-helm.org][Helm]]    | Incremental completion and selection framework |

#+begin_src emacs-lisp :exports none
;; Note order is important (init-hydra must be loaded before init-window).
(load-org-config "init-hydra.org")
(load-org-config "init-navigation.org")
(load-org-config "init-isearch.org")
(load-org-config "init-window.org")
(load-org-config "init-helm.org")
#+end_src

** Word processing

| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-text-mode.org][Text]]  | Global configuration for text modes |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-latex.org][LaTeX]] | Configurations for LaTeX development |

#+begin_src emacs-lisp :exports none
(load-org-config "init-latex.org")
(load-org-config "init-text-mode.org")
#+end_src

** Programming

| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-prog-mode.org][Programming]] | Global configuration for programming modes |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-projectile.org][Projectile]]  | Project management                         |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-git.org][Git]]         | Git configuration                          |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-ediff.org][Ediff]]       | Ediff configuration                        |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-python.org][Python]]      | Configurations for python development      |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-docker.org][Docker]]      | Docker configuration                       |
| [[https://github.com/asherbender/emacs-dot-files/blob/master/config/init-yaml.org][YAML]]        | Configurations for YAML development        |


#+begin_src emacs-lisp :exports none
(load-org-config "init-prog-mode.org")
;; (load-org-config "init-projectile.org")
(load-org-config "init-git.org")
(load-org-config "init-ediff.org")
(load-org-config "init-python.org")
(load-org-config "init-docker.org")
(load-org-config "init-yaml.org")
#+end_src

** Compiling Emacs from source

The Emacs sources can be retrieved from the [[https://ftp.gnu.org/pub/gnu/emacs/][FTP server]] of the the GNU project or
the development sources can be access via Git [[https://savannah.gnu.org/projects/emacs/][on Savannah]]. An overview of
compiling Emacs 29 on a Debian-based distribution is given here. For more
information, see the [[https://www.gnu.org/software/emacs/manual/html_node/efaq/Installing-Emacs.html][manual]] and the build instructions in the sources [[https://git.savannah.gnu.org/cgit/emacs.git/tree/INSTALL][INSTALL]]
file.

*** Clone the Emacs repository

#+BEGIN_SRC shell
  git clone git://git.savannah.gnu.org/emacs.git
  cd emacs
#+END_SRC

*** Checkout desired tag

#+BEGIN_SRC shell
  git checkout emacs-29.4
#+END_SRC

*** Install dependencies

#+BEGIN_SRC shell
  sudo apt install build-essential
  sudo apt build-dep emacs
  sudo apt install gcc-12 libgccjit0 libgccjit-12-dev libtree-sitter-dev
#+END_SRC

*** Review configuration options

#+BEGIN_SRC shell
  ./configure --help
#+END_SRC

*** Configure build

#+BEGIN_SRC shell
  ./autogen.sh
  CC="gcc-12" ./configure         \
    --build=x86_64-linux-gnu      \
    --with-x                      \
    --with-x-toolkit=gtk3         \
    --with-sound=alsa             \
    --without-mailutils           \
    --with-imagemagick            \
    --without-compress-install    \
    --with-tree-sitter            \
    --with-native-compilation=aot \
    --with-json
#+END_SRC

*** Compile

#+BEGIN_SRC shell
  make NATIVE_FULL_AOT=1 -j16
#+END_SRC

*** Install

#+BEGIN_SRC shell
  sudo make install
#+END_SRC
