* White space

- Set fill-column and use spaces instead of tabs when indenting
- Display whitespace primarily on overlength lines and TABS
- Simplify whitespace visualisations to prevent distractions
- Remove whitespace when a file is saved

** Tabs

#+BEGIN_SRC emacs-lisp
(setq-default fill-column 80)
(setq-default default-tab-width 2)
(setq-default indent-tabs-mode nil)
#+END_SRC

** White space configuration

Toggle whitespace visualization globally (do not display in mode-line).
#+BEGIN_SRC emacs-lisp
(global-whitespace-mode 1)
#+END_SRC

Specify which kind of blank is visualized:
- face :: enable visualization via faces.
- empty :: highlight empty lines at beginning and/or end of buffer.
- tabs :: highlight TAB space.
- tab-mark :: mark beginning of TAB.
- trailing :: highlight trailing blanks.
- lines-tail :: highlight the part of line which goes beyond
                `whitespace-line-column'.

#+BEGIN_SRC emacs-lisp
(use-package whitespace
  :diminish (global-whitespace-mode
             whitespace-mode
             whitespace-newline-mode)

  ;; Execute code before package is loaded.
  :init
  (progn

    ;; Specify whitespace to visualise.
    (setq whitespace-style '(face
                             empty
                             tabs
                             tab-mark
                             trailing
                             lines-tail))

    ;; Exclude modes from whitespace visualisation.
    (setq whitespace-global-modes '(not eshell-mode
                                        shell-mode
                                        dired-mode
                                        org-mode)
    )
  )

  ;; Execute code after package is loaded.
  :config
  (progn

    ;; Delete all trailing whitespace across the current buffer before saving.
    (add-hook 'before-save-hook 'delete-trailing-whitespace)
  )
)
#+END_SRC

** Appearance

Specify column beyond which the line is highlighted.
#+BEGIN_SRC emacs-lisp
(setq whitespace-line-column default-column-width)
#+END_SRC

Highlight tab characters in yellow.
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'whitespace-tab nil
                    :background "yellow")
#+END_SRC

Highlight trailing whitespace in yellow.
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'whitespace-line nil
                    :background "yellow"
                    :foreground "white")
#+END_SRC

Highlight the part of lines which goes beyond ‘whitespace-line-column’
column in yellow.
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'whitespace-line nil
                    :weight 'bold
                    :underline t
                    :background "white"
                    :foreground "red")
#+END_SRC
