* Minibuffer completion

Configure behaviour for saving minibuffer history:

#+BEGIN_SRC emacs-lisp
  ;; Toggle saving of minibuffer history.
  (savehist-mode 1)

  ;; File name where minibuffer history is saved to and loaded from.
  (setq savehist-file (concat user-emacs-auto-directory "minibuffer-history"))
#+END_SRC

** Minibuffer completion functions (backend)

#+BEGIN_QUOTE
Consult provides search and navigation commands based on the Emacs completion
function completing-read. Completion allows you to quickly select an item from a
list of candidates. Consult offers asynchronous and interactive =consult-grep=
and =consult-ripgrep= commands, and the line-based search command
=consult-line=. [[[https://github.com/minad/consult][source]]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package consult
    :ensure t
    :bind (("M-s"   . consult-line)
           ("C-x b" . consult-buffer)
          )
    :hook (completion-list-mode . consult-preview-at-point-mode)
    :custom
    (consult-preview-key '("M-."))
    (consult-narrow-key "<")
  )
#+END_SRC

#+BEGIN_QUOTE
Consult-project-extra provides an extension to the default Consult
functionality, using the built-in package =project.el=, defining the functions
=consult-project-extra-find= and
=consult-project-extra-find-other-window=. [[[https://github.com/minad/consult][source]]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package consult-project-extra
    :ensure t
    :bind
    (("C-x f" . consult-project-with-recentf-find))
    :config

    (defvar consult-project-extra--source-recent-file
      `(:name     "Recent Files"
        :narrow   (?r . "Recent files")
        :category file
        :face     consult-file
        :history  file-name-history
        :state    ,#'consult--file-state
        :new      ,#'consult--file-action
        :enabled  ,(lambda () recentf-mode)
        :items
        ,(lambda ()
           (let ((ht (consult--buffer-file-hash))
                 items)
             (dolist (file (bound-and-true-p recentf-list) (nreverse items))
               ;; Emacs 29 abbreviates file paths by default, see
               ;; `recentf-filename-handlers'.  I recommend to set
               ;; `recentf-filename-handlers' to nil to avoid any slow down.
               (unless (eq (aref file 0) ?/)
                 (let (file-name-handler-alist) ;; No Tramp slowdown please.
                   (setq file (expand-file-name file))))
               (unless (gethash file ht)
                 (push (consult--fast-abbreviate-file-name file) items))))))
      "Recent file candidate source for `consult-buffer'.")

    (defun consult-project-with-recentf-find ()
      "Search open buffers, project files, and recent files."
      (interactive)
      (let ((consult-project-extra-sources
             (append consult-project-extra-sources
                     (list consult-project-extra--source-recent-file))))
        (consult-project-extra-find))
    )
  )
#+END_SRC

** Minibuffer completion UI (frontend)

#+BEGIN_QUOTE
Vertico provides a performant and minimalistic vertical completion UI based on
the default completion system. The focus of Vertico is to provide a UI which
behaves correctly under all circumstances. By reusing the built-in facilities
system, Vertico achieves full compatibility with built-in Emacs completion
commands and completion tables. Vertico only provides the completion UI but aims
to be highly flexible, extendable and modular. [[[https://github.com/minad/vertico][source]]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package vertico
    :ensure t
    :init
    (vertico-mode)
    (vertico-mouse-mode)
    :custom
    (vertico-cycle t) ;; Allow cycling through candidates
  )
#+END_SRC

*** Annotate minibuffer completions

#+BEGIN_QUOTE
Marginalia are marks or annotations placed at the margin of the page of a book
or in this case helpful colorful annotations placed at the margin of the
minibuffer for your completion candidates. Marginalia can only add annotations
to the completion candidates. It cannot modify the appearance of the candidates
themselves, which are shown unaltered as supplied by the original
command. [[[https://github.com/minad/marginalia/][source]]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package marginalia
    :ensure t
    :init
    (marginalia-mode)
  )
#+END_SRC

*** Icons for minibuffer completions

#+BEGIN_QUOTE
Add icons to completion candidates using the built in completion metadata
functions. [[[https://github.com/iyefrat/all-the-icons-completion][source]]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons
    :ensure t
  )

  (use-package all-the-icons-completion
    :ensure t
    :after (marginalia all-the-icons)
    :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
    :init
    (all-the-icons-completion-mode)
  )
#+END_SRC

*** Minibuffer completion commands

#+BEGIN_QUOTE
Embark makes it easy to choose a command to run based on what is near point,
both during a minibuffer completion session (in a way familiar to Helm or
Counsel users) and in normal buffers. Bind the command =embark-act= to a key and
it acts like prefix-key for a keymap of actions (commands) relevant to the
target around point. [[[https://github.com/oantolin/embark][source]]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package embark
    :ensure t
    :bind
    (("C-." . embark-act)
     ("M-." . embark-dwim))
  )
#+END_SRC
