* Backup and auto-save

Create backup~ and #auto-save# files? Non-nil means:
- make a backup of a file the first time it is saved
- by default do auto-saving of every file-visiting buffer
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files  t)
  (setq auto-save-default  t)
#+END_SRC


** Backup

Place all =backup~= files in one directory.
#+BEGIN_SRC emacs-lisp
  (defcustom user-emacs-auto-backup
    (expand-file-name (file-name-as-directory "backup") user-emacs-auto-directory)
    "Directory for auto-backup files."
    :group 'user-emacs-auto
    :type 'directory)

  (unless (file-directory-p user-emacs-auto-backup)
    (make-directory user-emacs-auto-backup t))

  (setq backup-directory-alist `(("." . ,user-emacs-auto-backup)))
#+END_SRC

Always use copying to create backups.
#+BEGIN_SRC emacs-lisp
  (setq backup-by-copying t)
#+END_SRC

Delete excess backup versions silently.
#+BEGIN_SRC emacs-lisp
  (setq delete-old-versions t)
#+END_SRC

Control use of version numbers for backup files.
#+BEGIN_SRC emacs-lisp
  (setq version-control t)
#+END_SRC

Number of newest versions to keep when a new numbered backup is made.
Includes the new backup. Must be > 0 (default 2).
#+BEGIN_SRC emacs-lisp
  (setq kept-new-versions 10)
#+END_SRC

Do not backup files covered by version control.
#+BEGIN_SRC emacs-lisp
  (setq vc-make-backup-files nil)
#+END_SRC

** Auto-save

Place all =#auto-save#= files in one directory.
#+BEGIN_SRC emacs-lisp
  (defcustom user-emacs-auto-save
    (expand-file-name (file-name-as-directory "auto-save") user-emacs-auto-directory)
    "Directory for auto-save files."
    :group 'user-emacs-auto
    :type 'directory)

  (unless (file-directory-p user-emacs-auto-save)
    (make-directory user-emacs-auto-save t))

  (setq auto-save-list-file-prefix
    (concat user-emacs-auto-save ".saves-"))

  (setq auto-save-file-name-transforms `((".*" ,user-emacs-auto-save t)))
#+END_SRC

Number of seconds idle time before auto-save. Zero or nil means
disable auto-saving due to idleness. After auto-saving due to this
many seconds of idle time, Emacs also does a garbage collection if
that seems to be warranted (default: 30).
#+BEGIN_SRC emacs-lisp
  (setq auto-save-timeout 30)
#+END_SRC

Number of input events between auto-saves.  Zero means disable
autosaving due to number of characters typed (default: 300).
#+BEGIN_SRC emacs-lisp
  (setq auto-save-interval 300)
#+END_SRC
