* General settings

** User interface

This variable, if non-nil, inhibits the startup screen. If non-nil, Emacs
typically displays the ‘*scratch*’ buffer (see the variable
initial-buffer-choice).
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
#+END_SRC

Do not show tool-bar or scroll-bar on window systems.
#+BEGIN_SRC emacs-lisp
(when window-system
  (tooltip-mode     1)
  (tool-bar-mode   -1)
  (menu-bar-mode    1)
  (scroll-bar-mode -1)
)
#+END_SRC

Alias yes-or-no questions to y-or-n
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Use Global Font Lock mode to automagically turn on Font Lock mode
(contex highlighting) in buffers whose major mode supports it and
whose major mode is one of `font-lock-global-modes'.
#+BEGIN_SRC emacs-lisp
(global-font-lock-mode 1)
#+END_SRC

This makes the buffer scroll by only a single line when the up or down
cursor keys push the cursor outside the buffer. The standard emacs
behaviour is to reposition the cursor in the center of the screen, but
this can make the scrolling confusing.
#+BEGIN_SRC emacs-lisp
(setq scroll-step 1)
#+END_SRC

** Cursor line

Highlight the line containing the cursor in every buffer.
#+BEGIN_SRC emacs-lisp
(global-hl-line-mode 1)
(set-face-foreground 'hl-line "black")
(set-face-background 'hl-line "yellow")
#+END_SRC

** Selection behaviour

When Transient Mark mode is enabled, the region is highlighted
whenever the mark is active. The mark is "deactivated" by changing the
buffer, and after certain other operations that set the mark but whose
main purpose is something else--for example, incremental search, <,
and >. (In GNU Emacs 23 and onwards, it is enabled by default)
#+BEGIN_SRC emacs-lisp
(transient-mark-mode 1)
#+END_SRC

When Delete Selection mode is enabled, typed text replaces the
selection if the selection is active. Otherwise, typed text is just
inserted at point regardless of any selection.
#+BEGIN_SRC emacs-lisp
(delete-selection-mode 1)
#+END_SRC
